Feat1/week2
DO-SOPT-ANDROID/seyeon-cho pull request #5
Opened 2023-10-26 18:20 UTC by crownjoe

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯

- [ ] Multi-View Type RecyclerView

- [ ] 리스트 위에 기존 Friend 형식과는 다른 내 프로필을 디자인 해서 리스트 상단에 넣기
- [ ] 
- [ ] 바텀 네비게이션과 연동하기

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵

https://github.com/DO-SOPT-ANDROID/seyeon-cho/assets/135544903/159f500e-d0fc-4020-9c7c-73d236db0fc2

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
다들 시험 파이팅하세요!

2023-10-29 05:47 UTC, chattymin reviewed
이번주도 고생하셨습니다! 코드가 너무 깔끔하고 좋네용

2023-10-29 05:47 UTC, chattymin commented on app/src/main/java/org/sopt/dosopttemplate/MainAdapter.kt
> +    private val View_Friend = 1
상수로 사용하고자 하는거면 companion object를 활요해보는 것도 좋을 것 같습니당!

2023-10-29 05:47 UTC, chattymin commented on app/src/main/res/layout/fragment_my_page.xml
> +        app:layout_constraintTop_toBottomOf="@+id/image"
저는 1주차때 몰라서 이렇게 했었는데 여기서는 +를 빼야 할 것 같습니다!!
다른건 다 +없이 돼있는데 이것만 돼있네요. 잡았다 실수!

2023-10-29 06:59 UTC, lsakee requested changes
고생했습니다!!

2023-10-29 06:59 UTC, lsakee commented on app/src/main/java/org/sopt/dosopttemplate/DoAndroidFragment.kt
> +        _binding = null
_binding = null
super.onDestroyView()

2023-10-29 06:59 UTC, lsakee commented on app/src/main/java/org/sopt/dosopttemplate/HomeActivity.kt
> +                        replaceFragment(MyPageFragment.newInstance(user_id, user_major))
굿굿!

2023-10-29 06:59 UTC, lsakee commented on app/src/main/java/org/sopt/dosopttemplate/MyPageFragment.kt
> +        }
@JvmStatic이란 어노테이션을 추가 해주는 게 좋을 거 같습니둥 
컴패니언 오브젝트는 디컴파일시 컴패니언 클라스 내부에 생성되니 어노테이션을 통해 외부에도 생성되게 할 수 있습니다! 자바의 스태틱과 비슷하게 해줍니다

2023-10-29 09:52 UTC, stellar-halo reviewed
시험기간에 구현하느라 왕창 고생했어요!!

2023-10-29 09:52 UTC, stellar-halo commented on app/src/main/java/org/sopt/dosopttemplate/FriendViewHolder.kt
> +        binding.tvSelfMessage.text= userUserProfileData.message
with(binding) 써보시렵니까?

2023-10-29 09:52 UTC, stellar-halo commented on app/src/main/java/org/sopt/dosopttemplate/HomeActivity.kt
> +                        val errorMessage = "데이터가 없어요!."
companion object로 빼보시는 건 어때요?

2023-10-29 09:52 UTC, stellar-halo commented on app/src/main/java/org/sopt/dosopttemplate/HomeFragment.kt
> +        _binding = null
요부분도 조장님이 수정해주신 부분

2023-10-29 09:52 UTC, stellar-halo commented on app/src/main/java/org/sopt/dosopttemplate/HomeViewModel.kt
> +            message = "오늘 생일티비!"
고맙티비!💞

2023-10-29 09:52 UTC, stellar-halo commented on app/src/main/java/org/sopt/dosopttemplate/LoginActivity.kt
> +                enteredName = data?.getStringExtra("entered_Name") ?: ""
요런tag(?)도 string을 직접 넣어주지말고 보내주는 곳에서 companion object로 관리하면 편해요!

2023-10-29 09:52 UTC, stellar-halo commented on app/src/main/java/org/sopt/dosopttemplate/MainAdapter.kt
> +            else -> throw IllegalArgumentException("유효하지 않소")
그렇소

2023-10-29 09:52 UTC, stellar-halo commented on app/src/main/java/org/sopt/dosopttemplate/MyProfileViewHolder.kt
> +        binding.tvSelfMessage.text= userUserProfileData.message
with(binding),,ㅎㅎ

2023-10-29 09:52 UTC, stellar-halo commented on app/src/main/java/org/sopt/dosopttemplate/SignUpActivity.kt
> +        val editTextName = binding.editTextName
하나하나 넘겨주는 것도 좋지만~ data class를 만들어보는 건 어때요?

2023-10-29 09:52 UTC, stellar-halo commented on app/src/main/res/layout/activity_login.xml
> +    tools:context=".LoginActivity">
폴더링 한 번 해보실래요~?~

2023-10-29 09:52 UTC, stellar-halo commented on app/src/main/res/layout/activity_login.xml
> +        android:text="ID"
String,,,뺴,,주세요,,

2023-10-29 09:52 UTC, stellar-halo commented on app/src/main/res/layout/fragment_my_page.xml
> +        app:layout_constraintTop_toBottomOf="@+id/image"
@chattymin 뿌듯하군요 ^_^

2023-10-29 09:56 UTC, memoryBangwool commented on app/src/main/java/org/sopt/dosopttemplate/MyPageFragment.kt
> +        fun newInstance(id: String, major: String): MyPageFragment {
오 이렇게 정보를 넘겨줄 수 있구나..! 배워갑니다~

2023-10-29 09:58 UTC, memoryBangwool commented on app/src/main/java/org/sopt/dosopttemplate/HomeActivity.kt
> +                        replaceFragment(MyPageFragment.newInstance(user_id, user_major))
우와 배워갑니다!

2023-10-30 02:01 UTC, taeheeL commented on app/src/main/java/org/sopt/dosopttemplate/FriendViewHolder.kt
> +        binding.tvSelfMessage.text= userUserProfileData.message
ctrl + alt + L

2023-10-30 02:02 UTC, taeheeL commented on app/src/main/java/org/sopt/dosopttemplate/FriendViewHolder.kt
> +        binding.tvSelfMessage.text= userUserProfileData.message
Glide나 Coil 라이브러리 알아보면 좋을 것 같네요~

2023-11-02 10:55 UTC, Marchbreeze reviewed
코드 깔끔하네요~~~ 잘보구갑니다

2023-11-02 10:55 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/FriendViewHolder.kt
> +                .into(ivProfile)
Glide 사용도 좋은데, 요즘은 더 성능이 좋은 Coil 라이브러리를 활용하는 추세더라구요!

2023-11-02 10:55 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/HomeActivity.kt
> +                }
이렇게 되면 바텀네비게이션을 누를때마다 기존에 사용하던 프래그먼트가 있어도 새로운 프래그먼트들이 생성이 될 것 같은데, 불필요하게 새로운 프래그먼트를 생성하지 않는 방법에 대해서 생각해보면 좋을 것 같아요!

2023-11-02 10:55 UTC, Marchbreeze commented on app/src/main/java/org/sopt/dosopttemplate/SignUpActivity.kt
> +                finish()
스코프 함수를 활용하면 더 예쁜 코드를 만들 수 있습니닷~

2023-11-02 10:55 UTC, Marchbreeze commented on app/src/main/res/layout/activity_login.xml
> +        android:id="@+id/signupButton"
XML 네이밍을 할때는 꼭 Snake Case 규칙으로 작성해주세요! btn_sign_up 으로요~

2023-11-11 08:26 UTC, merged